routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BorrowController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\DonorController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlantController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SwapController;
use App\Http\Controllers\UserController;


Route::get('/', function () {
    return view('welcome');
})->name('welcome');

// Authentication Routes...
Route::get('login', [ LoginController::class, 'showLoginForm' ] )->name('login');
Route::post('login', [ LoginController::class, 'login' ] );
Route::post('logout', [ LoginController::class, 'logout' ] )->name('logout');

// Registration Routes...
Route::get('register', [ RegisterController::class, 'showRegistrationForm' ] )->name('register');
Route::post('register', [ RegisterController::class, 'register' ] );

// Password Reset Routes...
Route::get('password/reset', [ ForgotPasswordController::class, 'showLinkRequestForm' ] );
Route::post('password/email', [ ForgotPasswordController::class, 'sendResetLinkEmail' ] );
Route::get('password/reset/{token}', [ ResetPasswordController::class, 'showResetForm' ] );
Route::post('password/reset', [ ResetPasswordController::class, 'reset' ] );

Route::get('/home', [ HomeController::class, 'index' ] )->name('home');

// ADMINISTRACIÓN ///////////////////////////////////////////////////////////////
Route::get('admin/cut',[ AdminController::class, 'cut' ] )->name('admin.cut');
Route::get('admin/barcodes', [ AdminController::class, 'barcodes' ] )->name('admin.barcodes');
Route::post('admin/pdf', [ AdminController::class, 'pdf' ] )->name('admin.pdf');
Route::get('admin/search/book/{title}', [ AdminController::class, 'searchbook' ] );
Route::resource('admin', AdminController::class )->only([ 'edit', 'update' ]);

// REGISTROS
Route::get('user/pass/{id}', [ UserController::class, 'showPass' ] )->name('user.changepass');
Route::patch('user/updatepass/{id}', [ UserController::class, 'updatePass' ] )->name('user.updatePass');
Route::get('user/role/{id}', [ UserController::class, 'showRole' ] )->name('user.role');
Route::patch('user/updateRole/{id}', [ UserController::class, 'updateRole' ] )->name('user.updateRole');
Route::resource('users', UserController::class );

Route::put('book/updateStock', [ BookController::class, 'updateStock' ] )->name('book.updateStock');
Route::get('book/search', [ BookController::class, 'search' ] )->name('book.search');
Route::resource('books',BookController::class);
Route::get('feature/newFeature/{book_id}', [ FeatureController::class, 'newFeature' ] )->name('feature.newFeature');
Route::resource('features', FeatureController::class )->except([ 'index', 'create', 'show' ]);

Route::resource('classifications', ClassificationController::class )->except([ 'show' ]);
Route::resource('clients', ClientController::class );
Route::resource('plants', PlantController::class );

// OPERACIONES //////////////////////////////////////////////////////////////////
Route::get('swap/search/book/{isbn}', [ SwapController::class, 'searchbook' ] );
Route::resource('swaps', SwapController::class );

Route::get('donation/donate', [ DonationController::class, 'donate' ] )->name('donation.donate');
Route::get('donation/receive', [ DonationController::class, 'receive' ] )->name('donation.receive');
Route::resource('donations', DonationController::class )->except([ 'create', 'edit', 'update' ]);
Route::resource('donors', DonorController::class )->except([ 'show' ]);

Route::get('borrow/search/book/{isbn}', [ BorrowController::class, 'searchbook' ] );
Route::get('devolution/search/book/{isbn}', [ BorrowController::class, 'searchborrowedbook' ] )->name('devolution.search.book');
Route::resource('borrows', BorrowController::class )->except([ 'destroy' ]);

// VENTAS ///////////////////////////////////////////////////////////////////////
Route::get('sale/search/book/{isbn}', [ SaleController::class, 'searchbook' ] )->name('searchbook');
Route::get('sale/search/plant/{id}', [ SaleController::class, 'searchplant' ] )->name('searchplant');
Route::resource('sales', SaleController::class )->except([ 'edit', 'update', 'destroy' ]);
/////////////////////////////////////////////////////////////////////////////////

app/Models/Donor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Donor extends Model
{
	protected $table = 'donors';
	
    protected $fillable = [ 'institution', 'contact', 'email', 'phone', 'address', 'commercial_business' ];

    public $timestamps = false;

    protected function donations()
    {
    	return $this->hasMany(Donation::class, 'donor_id', 'id');
    } 

    public function getDonor() 
    {
    	return $this->institution.' : '.$this->contact;
    }
}

app/Http/Controllers/DonorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Models\Donor;
use App\Models\Classification;

class DonorController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * función para renderizar la lista de donadores
     * 
     * @return View con la lista de todos los donadores registrados en la plataforma
     */
    public function index()
    {
        return view('donors.index_donors', [ 'donors' => Donor::all() ]);
    }

    /**
     * función para renderizar la vista del formulario de creación de donadores
     * 
     * @return View del formulario de creación
     */
    public function create()
    {
        return view('donors.create_donor');
    }

    /**
     * función para almacenar la información de nuevos donadores registrados
     * 
     * @param Request con la información de los nuevos donadores
     * @return Redirect hacía la lista de todos los donadores creados junto con el mensaje correspondiente
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all() , [
            'contact' => 'required|max:50'
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }
        Donor::create($request->all());
        return redirect()->action([ DonorController::class, 'index' ])->with('success','El contacto se registro correctamente...');
    }

    /**
     * función para renderizar la vista del formulario de edición de donadores
     * 
     * @param Integer con el $id del donador a modificar
     * @return View con el formulario de edición con la información del donador a modificar
     */
    public function edit($id)
    {
        return view('donors.edit_donor', [ 'donor' => Donor::findOrFail($id) ]);
    }

    /**
     * función para actualizar la información de los donadores almacenados
     * 
     * @param Request con la nueva información del donador
     * @param Integer con el $id del donador a modificar
     * @return View hacía la lista de los donadores con el mensaje de la operación
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'contact' => 'required|max:50'
        ]);

        if($validator->fails())
            return redirect()->back()->withErrors($validator->errors())->withInput();

        Donor::where('id',$id)->update($request->except('_token','_method'));
        return redirect()->action([ DonorController::class, 'index' ])->with('edit','El contacto se ha modificado exitosamente!...');
    }

    /**
     * función para eliminar donadores 
     * 
     * @param Integer con el $id del donador a eliminar
     * @return Redirect hacía la lista de los donadores con el mensaje de la operación
     */
    public function destroy($id)
    {
        Donor::findOrFail($id)->delete();
        return redirect()->action([ DonorController::class, 'index' ])->with('delete','El contacto se ha eliminado exitosamente!...');
    }
}

resources/views/donors/create_donor.blade.php
@extends('layouts.theme')

@section('title', 'Registro de Institución/Contacto')

@section('content-header')
	<h1>
		<div class="col-md-8"><strong> Registro de Institución / Contacto </strong></div>
    </h1><hr>
@endsection

@section('content')

	@include('partials.errors')

	<form role="form" action="{{ route('donors.store') }}" method="POST">
		{{ csrf_field() }}
		<div class="box-body">
			<div class="form-group col-md-6">
				<label for="institution"> Institucion </label>
				<input class="form-control" type="text" name="institution" id="institution" value="{{ old('institution') }}">
			</div>
			<div class="form-group col-md-6">
				<label for="contact"> Contacto </label>
				<input class="form-control" type="text" name="contact" id="contact" value="{{ old('contact') }}" required>
			</div>
			<div class="form-group col-md-6">
				<label for="email"> Correo </label>
				<input class="form-control" type="email" name="email" id="email" value="{{ old('email') }}">
			</div>
			<div class="form-group col-md-6">
				<label for="phone"> Teléfono </label>
				<input class="form-control" type="number" min=10000000 max=9999999999 name="phone" id="phone" value="{{ old('phone') }}">
			</div>
			<div class="form-group col-md-6">
				<label for="address"> Dirección </label>
				<input class="form-control" type="text" name="address" id="address" value="{{ old('address') }}">
			</div>
			<div class="form-group">
				<div class="col-md-6">
					<label for="commercial_business"> Actividad </label>
					<input class="form-control" type="text" name="commercial_business" id="commercial_business" value="{{ old('commercial_business') }}">
				</div>
			</div>
		</div> <!-- /. class="box-body" -->
		<div class="box-footer">
			<button type="submit" class="btn btn-primary btn-block"> Guardar </button>
			<a class="btn btn-danger btn-block" href="{{ route('donors.index') }}"> Cancelar </a>
		</div> <!-- /. class="box-footer" -->
	</form>

@endsection

@section('scripts')
	<script src="{{ asset('js/functions/typeNumber.js') }}"></script>
@endsection

resources/views/donors/edit_donor.blade.php
@extends('layouts.theme')

@section('title', 'Edición de Contacto')

@section('content-header')
	<h1><div class="col-md-8"><strong> Edición de Contacto : {{ $donor->id }} </strong></div></h1><hr>
@endsection

@section('content')
	
	@include('partials.errors')

	<form role="form" action="{{ route('donors.update', $donor->id) }}" method="POST">
		{{ csrf_field() }}
		<div class="box-body">
			<input name="_method" type="hidden" value="PATCH">
			<div class="form-group col-md-6">
				<label for="institution"> Institucion </label>
				<input class="form-control" type="text" name="institution" id="institution" value="{{ $donor->institution }}">
			</div>
			<div class="form-group col-md-6">
				<label for="contact"> Contacto </label>
				<input class="form-control" type="text" name="contact" id="contact" value="{{ $donor->contact }}" required>
			</div>
			<div class="form-group col-md-6">
				<label for="email"> Correo </label>
				<input class="form-control" type="email" name="email" id="email" value="{{ $donor->email }}">
			</div>
			<div class="form-group col-md-6">
				<label for="phone"> Teléfono </label>
				<input class="form-control" type="number" name="phone" id="phone" value="{{ $donor->phone }}">
			</div>
			<div class="form-group col-md-6">
				<label for="address"> Dirección </label>
				<input class="form-control" type="text" name="address" id="address" value="{{ $donor->address }}">
			</div>
			<div class="form-group">
				<div class="col-md-6">
					<label for="commercial_business"> Actividad </label>
					<input class="form-control" type="text" name="commercial_business" id="commercial_business" value="{{ $donor->commercial_business }}">
				</div>
			</div>
		</div> <!-- /. class="box-body" -->
		<div class="box-footer">
			<button type="submit" class="btn btn-primary btn-block"> Guardar </button>
			<a class="btn btn-danger btn-block" href="{{ route('donors.index') }}"> Cancelar </a>
		</div> <!-- /. class="box-footer" -->
	</form>

@endsection

@section('scripts')
	<script src="{{ asset('js/functions/typeNumber.js') }}"></script>
@endsection

resources/views/donors/index_donors.blade.php
@extends('layouts.theme')

@section('title', 'Instituciones / Contactos')

@section('styles')
    <link rel="stylesheet" href="{{ asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content-header')
    <h1>
        <div class="col-md-6"><strong>Instituciones y Contactos Registrados</strong></div>
        <div class="col-md-2">
            <a class="btn btn-block pull-right" href="{{ route('donations.index') }}">
            <i class="fa fa-gift"></i> DONACIONES </a>
        </div>
        <div class="col-md-4">
            <a class="btn btn-success btn-block pull-right" href="{{ route('donors.create') }}">
            <i class="fa fa-pencil-square-o"></i> NUEVA INSTITUCIÓN O CONTACTO </a>
        </div>
    </h1>
    <hr>
@endsection

@section('content')

    @include('partials.success')
    @include('partials.delete')
    @include('partials.edit')

    @if($donors->isEmpty())
        <div class="col-md-12">
            <div class="alert alert-warning">
                <i class="icon fa fa-warning"></i> No hay instituciones o contactos registrados...
            </div>
        </div>
    
    @else
        <div class="box">
            <div class="box-body">
                <table id="donations_table" class="table table-bordered table-striped">
                    <thead>
                        <tr class="success">
                            <th> ID </th>
                            <th> Institución </th>
                            <th> Contacto </th>
                            <th> Correo </th>
                            <th> Telefono </th>
                            <th> Dirección </th>
                            <th> Actividad </th>
                            <!-- <th>  </th> -->
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($donors as $donor)
                            <tr>
                                <td><a class="btn btn-block btn-sm bg-olive" href="{{ route('donors.edit', $donor->id) }}">{{ $donor->id }}</a></td> 
                                <td>{{ $donor->institution }}</td>
                                <td>{{ $donor->contact }}</td>
                                <td>{{ $donor->email }}</td>
                                <td>{{ $donor->phone }}</td>
                                <td>{{ $donor->address }}</td>
                                <td>{{ $donor->commercial_business }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table> <!-- /. id="donations_table" -->
            </div> <!-- /. class="box-body" -->
        </div> <!-- /. class="box" -->
    @endif
@endsection

@section('scripts')
    <script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script>
      $(function () {
        $('#donations_table').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : true
        })
      })
    </script>
@endsection