routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BorrowController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\DonorController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlantController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SwapController;
use App\Http\Controllers\UserController;


Route::get('/', function () {
    return view('welcome');
})->name('welcome');

// Authentication Routes...
Route::get('login', [ LoginController::class, 'showLoginForm' ] )->name('login');
Route::post('login', [ LoginController::class, 'login' ] );
Route::post('logout', [ LoginController::class, 'logout' ] )->name('logout');

// Registration Routes...
Route::get('register', [ RegisterController::class, 'showRegistrationForm' ] )->name('register');
Route::post('register', [ RegisterController::class, 'register' ] );

// Password Reset Routes...
Route::get('password/reset', [ ForgotPasswordController::class, 'showLinkRequestForm' ] );
Route::post('password/email', [ ForgotPasswordController::class, 'sendResetLinkEmail' ] );
Route::get('password/reset/{token}', [ ResetPasswordController::class, 'showResetForm' ] );
Route::post('password/reset', [ ResetPasswordController::class, 'reset' ] );

Route::get('/home', [ HomeController::class, 'index' ] )->name('home');

// ADMINISTRACIÓN ///////////////////////////////////////////////////////////////
Route::get('admin/cut',[ AdminController::class, 'cut' ] )->name('admin.cut');
Route::get('admin/barcodes', [ AdminController::class, 'barcodes' ] )->name('admin.barcodes');
Route::post('admin/pdf', [ AdminController::class, 'pdf' ] )->name('admin.pdf');
Route::get('admin/search/book/{title}', [ AdminController::class, 'searchbook' ] );
Route::resource('admin', AdminController::class )->only([ 'edit', 'update' ]);

// REGISTROS
Route::get('user/pass/{id}', [ UserController::class, 'showPass' ] )->name('user.changepass');
Route::patch('user/updatepass/{id}', [ UserController::class, 'updatePass' ] )->name('user.updatePass');
Route::get('user/role/{id}', [ UserController::class, 'showRole' ] )->name('user.role');
Route::patch('user/updateRole/{id}', [ UserController::class, 'updateRole' ] )->name('user.updateRole');
Route::resource('users', UserController::class );

Route::put('book/updateStock', [ BookController::class, 'updateStock' ] )->name('book.updateStock');
Route::get('book/search', [ BookController::class, 'search' ] )->name('book.search');
Route::resource('books',BookController::class);
Route::get('feature/newFeature/{book_id}', [ FeatureController::class, 'newFeature' ] )->name('feature.newFeature');
Route::resource('features', FeatureController::class )->except([ 'index', 'create', 'show' ]);

Route::resource('classifications', ClassificationController::class )->except([ 'show' ]);
Route::resource('clients', ClientController::class );
Route::resource('plants', PlantController::class );

// OPERACIONES //////////////////////////////////////////////////////////////////
Route::get('swap/search/book/{isbn}', [ SwapController::class, 'searchbook' ] );
Route::resource('swaps', SwapController::class );

Route::get('donation/donate', [ DonationController::class, 'donate' ] )->name('donation.donate');
Route::get('donation/receive', [ DonationController::class, 'receive' ] )->name('donation.receive');
Route::resource('donations', DonationController::class )->except([ 'create', 'edit', 'update' ]);
Route::resource('donors', DonorController::class )->except([ 'show' ]);

Route::get('borrow/search/book/{isbn}', [ BorrowController::class, 'searchbook' ] );
Route::get('devolution/search/book/{isbn}', [ BorrowController::class, 'searchborrowedbook' ] )->name('devolution.search.book');
Route::resource('borrows', BorrowController::class )->except([ 'destroy' ]);

// VENTAS ///////////////////////////////////////////////////////////////////////
Route::get('sale/search/book/{isbn}', [ SaleController::class, 'searchbook' ] )->name('searchbook');
Route::get('sale/search/plant/{id}', [ SaleController::class, 'searchplant' ] )->name('searchplant');
Route::resource('sales', SaleController::class )->except([ 'edit', 'update', 'destroy' ]);
/////////////////////////////////////////////////////////////////////////////////

app/Models/Plant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Plant extends Model
{
    protected $fillable = [ 'name', 'price', 'image', 'tips', 'stock', 'classification_id' ];

    public $timestamps = false;

    protected $table = 'plants';

    public function classification()
    {
        return $this->hasOne(Classification::class, 'id', 'classification_id')
                    ->withDefault([
                                    'name' => 'eliminada', 
                                    'type' => 'Libro'
                                ]);
    }

    public function getInfo()
    {
        return $this->name.' :: Precio: $'.$this->price;
    }

}

app/Http/Controllers/PlantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Plant;
use App\Models\Classification;

class PlantController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * función para listar todas las plantas almacenadas en la base de datos
     * 
     * @return View con todas las plantas
     */
    public function index()
    {
        return view('plants.index_plants', [ 'plants' => Plant::all() ]);
    }

    /**
     * función para renderizar el formulario de creación de nuevas plantas
     * 
     * @return View con el formulario y la lista de clases del tipo de plantas que se pueden registrar
     */
    public function create()
    {
        return view('plants.create_plant', [ 'classes' => Classification::orderBy('name')->where('type', 'Planta')->get() ]);
    }

    /**
     * función para almacenar nuevas plantas en la base de datos
     * 
     * @param Request con la información de nuevas plantas a almacenar
     * @return Redirect hacía la vista de la lista de todas las plantas almacenadas con el mensaje de la operación de registro
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'price' => 'required|numeric|min:5',
            'tips' => 'required',
            //'image' => 'required',//'mimes:jpeg,png',
            'stock' => 'required|integer|min:1',
            'classification_id' => 'required',
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        //$i = ($request->file('image')->store('public'));
        //$plant->image = $i;

        Plant::create($request->all());
        return redirect()->action([ PlantController::class, 'index'] )->with('success', 'La planta se ha registrado exitosamente!...');
    }

    /**
     * función para mostrar los detalles de las plantas 
     * 
     * @param Integer con el $id de la planta a mostrar
     * @return View con la vista de los detalles de la planta a mostrar
     */
    public function show($id)
    {
        return view('plants.show_plant', [ 'plant' => Plant::findOrFail($id) ] );
    }

    /**
     * función para renderizar la vista del formulario de edición de plantas 
     * 
     * @param Integer con el $id de la planta a editar
     * @return View con el formulario de edición, la información de la planta a editar y la información de las clases de platantas que se pueden modificar
     */
    public function edit($id)
    {
        return view('plants.edit_plant', [ 'plant' => Plant::findOrFail($id), 'classes' => Classification::orderBy('name')->where('type','Planta')->get() ]);
    }

    /**
     * función para actualizar la información de las plantas ya creadas en la base de datos
     * 
     * @param Request con la nueva información de la planta
     * @param Integer con el $id de la planta a modificar
     * @return Redirect hacía la vista de los detalles de la planta modificada y el mensaje de la operación de modificación
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'price' => 'required|numeric|min:5',
            'tips' => 'required',
            //'image' => 'required', // mimes:jpeg,png
            'stock' => 'required|integer|min:1',
            'classification_id' => 'required',
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        Plant::where('id',$id)->update($request->except('_token','_method'));
        return redirect()->action([ PlantController::class, 'show' ], $id)->with('edit','La planta se ha modificado exitosamente!...');
    }

    /**
     * función para eliminar de la base de datos las plantas
     * 
     * @return Redirect hacía la lista de plantas con el mensaje de la operación
     */
    public function destroy($id)
    {
        Plant::findOrFail($id)->delete();
        return redirect()->action([ PlantController::class, 'index' ])->with('delete', 'La planta se ha eliminado correctamente!...');
    }
}

resources/views/plants/create_plant.blade.php
@extends('layouts.theme')

@section('title', 'Registro de Plantas')

@section('content-header')
	<h1><div class="col-md-8"><strong> Registro de Plantas </strong></div></h1><hr>
@endsection

@section('content')

	@include('partials.errors')

	<form role="form" action="{{ route('plants.store') }}" method="POST">
		{{ csrf_field() }}
		<div class="box-body">
			<div class="form-group col-md-12">
				<label for="name"> Nombre: </label>
				<input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}">
			</div> <!-- /. class="form-group col-md-12" -->
			<div class="form-group">
				<div class="col-md-8">
					<label for="tips"> Recomendaciones: </label>
					<input class="form-control" type="text" name="tips" id="tips" value="{{ old('tips') }}">
				</div>
			</div> <!-- /. class="form-group" -->
			<div class="form-group">
				<div class="col-md-4">
					<label for="classification"> Clasificación: </label>
	                <select class="form-control select2" style="width:100%;" name="classification_id" id="classification_id" value="{{ old('classification_id') }}">
	                  	<option value="" selected="disabled"> </option>
	                  	@foreach($classes as $class)
	                  		<option value="{{ $class->id }}"> {{ $class->name }} </option>
						@endforeach
					</select>
            	</div>
            	<div class="col-md-3">
					<label for="stock"> Stock: </label>
					<input class="form-control" type="text" name="stock" id="stock" value="{{ old('stock') }}">
				</div>
				<div class="col-md-3">
					<label for="price"> Precio: </label>
					<div class="input-group">
						<span class="input-group-addon"> $ </span>
						<input class="form-control" type="text" name="price" id="price" value="{{ old('price') }}">
					</div>
				</div>
			</div> <!-- /. class="form-group" -->
			{{--
			<div class="form-group">
				<div class="col-md-6">
					<label for="image"> Imagen: </label>
					<input class="form-control" type="file" name="image" id="image" value="{{ old('image') }}">
				</div>
			</div> 
			--}}
		</div> <!-- /. class="box-body" -->

		<div class="box-footer">
			<button type="submit" class="btn btn-primary btn-block"> Registrar </button>
			<a class="btn btn-danger btn-block" href="{{ route('plants.index') }}"> Cancelar </a>
		</div> <!-- /. class="box-footer" -->
	</form>

@endsection

@section('scripts')
	<script src="{{ asset('js/functions/typeNumber.js') }}"></script>
@endsection

resources/views/plants/edit_plant.blade.php
@extends('layouts.theme')

@section('title', 'Edición de Planta')

@section('content-header')
	<h1><div class="col-md-8"><strong> Edición de Planta : {{ $plant->id }} </strong></div></h1><hr>
@endsection

@section('content')

	@include('partials.errors')

	<form role="form" action="{{ route('plants.update', $plant->id) }}" method="POST">
		{{ csrf_field() }}
		<div class="box-body">

			<input name="_method" type="hidden" value="PATCH">

			<div class="form-group col-md-12">
				<label for="name"> Nombre </label>
				<input type="text" class="form-control" id="name" name="name" value="{{ $plant->name }}">
			</div> <!-- /. class="form-group col-md-12" -->

			<div class="form-group">
				<div class="col-md-8">
					<label for="tips"> Recomendaciones </label>
					<input type="text" class="form-control" id="tips" name="tips" value="{{ $plant->tips }}">
				</div>
				<div class="col-md-4">
					<label for="classification"> Clasificación </label>
					<select class="form-control select2" style="width:100%;" name="classification_id" id="classification_id" value="{{ $plant->classification->id }}">
						<option value="{{ $plant->classification->id }}" selected="disabled"> {{ $plant->classification->name }} </option>
						@foreach($classes as $class)
							<option value="{{ $class->id }}"> {{ $class->name }} </option>
						@endforeach
					</select>
				</div> 
			</div> <!-- /. class="form-group" -->

			<div class="form-group">
				<div class="col-md-4">
					<label for="stock"> Stock </label>
					<input class="form-control" type="text" name="stock" id="stock" value="{{ $plant->stock }}">
				</div>
				<div class="col-md-4">
					<label for="price"> Precio </label>
					<div class="input-group">
						<span class="input-group-addon"> $ </span>
						<input class="form-control" type="text" name="price" id="price" value="{{ $plant->price }}">
					</div>
				</div>
				{{--
				<div class="col-md-4">
					<label for="image"> Imagen </label>
					<input class="form-control" type="text" name="image" id="image" value="{{ $plant->image }}">
				</div>
				--}}
			</div> <!-- /. class="form-group" -->

		</div> <!-- /. class="box-body" -->

		<div class="box-footer">
			<button type="submit" class="btn btn-primary btn-block"> Guardar </button>
			<a class="btn btn-danger btn-block" href="{{ route('plants.show', $plant->id) }}"> Cancelar </a>
		</div> <!-- /. class="box-footer" -->
		
	</form>

@endsection

@section('scripts')
	<script src="{{ asset('js/functions/typeNumber.js') }}"></script>
@endsection

resources/views/plants/index_plants.blade.php
@extends('layouts.theme')

@section('title', 'Plantas')

@section('styles')
    <link rel="stylesheet" href="{{ asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('scripts')
    <script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script>
        $(function () {
            $('#plants_table').DataTable({
            'paging'      : true,
            'lengthChange': true,
            'searching'   : true,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : true
            })
        })
    </script>
@endsection

@section('content-header') 
    <h1>
        <div class="col-md-8">
            <strong>Lista de Plantas</strong>
        </div>
        <div class="col-md-4">
            <a class="btn btn-success btn-block pull-right" href="{{ route('plants.create') }}">
            <i class="fa  fa-pencil-square-o"></i> NUEVO REGISTRO </a>
        </div>
    </h1>
    <hr>
@endsection

@section('content')

    @include('partials.success')
    @include('partials.delete')

    @if($plants->isEmpty())
        <div class="col-md-12">
            <div class="alert alert-warning">
                <i class="icon fa fa-warning"></i> No hay plantas registradas...
            </div>
        </div>
    
    @else
        <table id="plants_table" class="table table-condensed">
            <thead>
                <tr class="success">
                    <th> ID </th>
                    <th> Planta </th>
                    <th> Stock </th>
                </tr>
            </thead>
            <tbody>
                @foreach($plants as $plant)
                    <tr>
                        <td><a class="btn btn-sm btn-block bg-olive" href="{{ route('plants.show', $plant->id) }}">{{ $plant->id }}</a></td>
                        <td>{{ $plant->name }}</td>
                        <td>{{ $plant->stock }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table> <!-- /. id="plants_table" -->
    @endif
@endsection

resources/views/plants/show_plant.blade.php
@extends('layouts.theme')

@section('title', 'Plantas')

@section('content-header')
    <h1><div class="col-md-8"><strong>Info. de Planta</strong></div></h1><hr>
@endsection

@section('content')

    @include('partials.error')
    @include('partials.edit')

    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-header with-border">
                <h1 class="box-title"> {{ $plant->name }} </h1>
            </div> <!-- /. class="box-header with-border" -->
            <div class="box-body">
                <div class="col-md-6">
                    <dl class="dl-horizontal">
                        <dt>Precio:</dt><dd>{{ "$ ".$plant->price }}</dd>
                        <dt>Clasificación:</dt><dd>{{ $plant->classification->name }}</dd>
                        <dt>Recomendaciones:</dt><dd>{{ $plant->tips }}</dd>
                        <dt>Stock:</dt><dd>{{ $plant->stock }}</dd>
                    </dl>
                </div> 
                <div class="col-md-6">
                    <!-- <img src="{ { Storage::url($plant->image) }}" width="50%"></a>-->
                </div>
            </div> <!-- /. class="box-body" -->
        </div> <!-- /. class="box box-solid" -->

        <div class="col-md-13">
            <div class="box box-primary">
                <div class="box-footer">
                    <a class="btn btn-primary col-md-6" href="{{ route('plants.index') }}"> Aceptar </a>
                    <a class="btn btn-success col-md-6" href="{{ route('plants.edit', $plant->id) }}"> Editar </a>
                </div>
            </div> <!-- /. class="box box-primary" -->
        </div> <!-- /. class="col-md-13" -->

    </div> <!-- /. class="col-md-12" -->
@endsection