routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BorrowController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\DonorController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlantController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SwapController;
use App\Http\Controllers\UserController;


Route::get('/', function () {
    return view('welcome');
})->name('welcome');

// Authentication Routes...
Route::get('login', [ LoginController::class, 'showLoginForm' ] )->name('login');
Route::post('login', [ LoginController::class, 'login' ] );
Route::post('logout', [ LoginController::class, 'logout' ] )->name('logout');

// Registration Routes...
Route::get('register', [ RegisterController::class, 'showRegistrationForm' ] )->name('register');
Route::post('register', [ RegisterController::class, 'register' ] );

// Password Reset Routes...
Route::get('password/reset', [ ForgotPasswordController::class, 'showLinkRequestForm' ] );
Route::post('password/email', [ ForgotPasswordController::class, 'sendResetLinkEmail' ] );
Route::get('password/reset/{token}', [ ResetPasswordController::class, 'showResetForm' ] );
Route::post('password/reset', [ ResetPasswordController::class, 'reset' ] );

Route::get('/home', [ HomeController::class, 'index' ] )->name('home');

// ADMINISTRACIÓN ///////////////////////////////////////////////////////////////
Route::get('admin/cut',[ AdminController::class, 'cut' ] )->name('admin.cut');
Route::get('admin/barcodes', [ AdminController::class, 'barcodes' ] )->name('admin.barcodes');
Route::post('admin/pdf', [ AdminController::class, 'pdf' ] )->name('admin.pdf');
Route::get('admin/search/book/{title}', [ AdminController::class, 'searchbook' ] );
Route::resource('admin', AdminController::class )->only([ 'edit', 'update' ]);

// REGISTROS
Route::get('user/pass/{id}', [ UserController::class, 'showPass' ] )->name('user.changepass');
Route::patch('user/updatepass/{id}', [ UserController::class, 'updatePass' ] )->name('user.updatePass');
Route::get('user/role/{id}', [ UserController::class, 'showRole' ] )->name('user.role');
Route::patch('user/updateRole/{id}', [ UserController::class, 'updateRole' ] )->name('user.updateRole');
Route::resource('users', UserController::class );

Route::put('book/updateStock', [ BookController::class, 'updateStock' ] )->name('book.updateStock');
Route::get('book/search', [ BookController::class, 'search' ] )->name('book.search');
Route::resource('books',BookController::class);
Route::get('feature/newFeature/{book_id}', [ FeatureController::class, 'newFeature' ] )->name('feature.newFeature');
Route::resource('features', FeatureController::class )->except([ 'index', 'create', 'show' ]);

Route::resource('classifications', ClassificationController::class )->except([ 'show' ]);
Route::resource('clients', ClientController::class );
Route::resource('plants', PlantController::class );

// OPERACIONES //////////////////////////////////////////////////////////////////
Route::get('swap/search/book/{isbn}', [ SwapController::class, 'searchbook' ] );
Route::resource('swaps', SwapController::class );

Route::get('donation/donate', [ DonationController::class, 'donate' ] )->name('donation.donate');
Route::get('donation/receive', [ DonationController::class, 'receive' ] )->name('donation.receive');
Route::resource('donations', DonationController::class )->except([ 'create', 'edit', 'update' ]);
Route::resource('donors', DonorController::class )->except([ 'show' ]);

Route::get('borrow/search/book/{isbn}', [ BorrowController::class, 'searchbook' ] );
Route::get('devolution/search/book/{isbn}', [ BorrowController::class, 'searchborrowedbook' ] )->name('devolution.search.book');
Route::resource('borrows', BorrowController::class )->except([ 'destroy' ]);

// VENTAS ///////////////////////////////////////////////////////////////////////
Route::get('sale/search/book/{isbn}', [ SaleController::class, 'searchbook' ] )->name('searchbook');
Route::get('sale/search/plant/{id}', [ SaleController::class, 'searchplant' ] )->name('searchplant');
Route::resource('sales', SaleController::class )->except([ 'edit', 'update', 'destroy' ]);
/////////////////////////////////////////////////////////////////////////////////

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table = 'clients';
    
    protected $fillable = [ 'name', 'email', 'phone', 'interests', 'type' ];

    public $timestamps = false;

    public function borrows()
    {
    	return $this->hasMany(Borrow::class, 'client_id', 'id');
    }

    public function invoices()
    {
        return $this->hasMany(Invoice::class, 'client_id', 'id');
    }

    public function getInfo()
    {
    	return $this->name.' : '.$this->email;
    }

}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Models\Client;

class ClientController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * función para listar a los clientes registrados en la plataforma
     * 
     * @return View con todos los clientes registrados
     */
    public function index()
    {
        return view('clients.index_clients', [ 'clients' => Client::all() ]);
    }

    /**
     * función para renderizar la vista para crear clientes nuevos
     * 
     * @return View del formulario de creación de nuevos clientes
     */
    public function create()
    {
        return view('clients.create_client');
    }

    /**
     * función para almacenar en la base de datos los nuevos clientes creados, solo los usuarios del sistema son capaces de crear a los clientes
     * 
     * @param Request con la información del cliente creado
     * @return Redirect hacia la lista de clietnes creados
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:50',
            //'email' => 'required|unique:clients',
            //'phone' => 'required|digits:10',
            //'interests' => 'required|max:50',
            'type' => 'required',
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        Client::create($request->all());
        return redirect()->action([ ClientController::class, 'index' ])->with('success', 'El cliente se ha registrado exitosamente!...');
    }

    /**
     * función para mostrar el detalle de los clientes registrados en la plataforma
     * 
     * @param Integer con el $id del cliente a mostrar
     * @return View con la información del cliente alcanzado
     */
    public function show($id)
    {
        return view('clients.show_client', [ 'client' => Client::findOrFail($id) ]);
    }

    /**
     * función para renderizar el formulario de edición de clientes registrados
     * 
     * @param Integer con el $id del cliente a modificar
     * @return View con el formulario de edición y la información del cliente a modificar
     */
    public function edit($id)
    {
        return view('clients.edit_client', [ 'client' => Client::findOrFail($id) ]);
    }

    /**
     * función para actualizar la información de los clientes registrados en la base de datos
     * 
     * @param Request con la nueva información del cliente a modificar
     * @param Integer con el $id del cliente a actualizar
     * @return Redirect hacia el detalle del cliente modificado con el mensaje correspondiente
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:50',
            'email' => 'required|unique:clients,email,'.$id,
            'phone' => 'required|size:10',
            'type' => 'required',
            'interests' => 'required'
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        Client::where('id',$id)->update($request->except('_token','_method'));
        return redirect()->action([ ClientController::class, 'show' ], $id)->with('edit', 'El cliente se ha modificado exitosamente!...');
    }

    /**
     * función para eliminar a los clientes registrados en la base de datos
     * 
     * @param Integer con el $id del cliente a eliminar
     * @return Redirect hacia la lista de los clientes registrados y con la información de la operación
     */
    public function destroy($id)
    {
        Client::findOrFail($id)->delete();
        return redirect()->action([ ClientController::class, 'index' ])->with('delete', 'El cliente se ha eliminado exitosamente!...');
    }
}

resources/views/clients/create_client.blade.php
@extends('layouts.theme')

@section('title', 'Registro de Clientes')

@section('content-header')
	<h1><div class="col-md-8"><strong> Registro de Clientes </strong></div></h1><hr>
@endsection

@section('content')

	@include('partials.errors') 

	<form role="form" action="{{ route('clients.store') }}" method="POST">
		{{ csrf_field() }}
		<div class="box-body">
			<div class="form-group col-md-12">
				<label for="name"> Nombre </label>
				<input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}">
			</div> <!-- /. class="form-group col-md-12" -->
			<div class="form-group">
				<div class="col-md-4">
					<label for="email"> E-Mail </label>
					<input class="form-control" type="email" name="email" id="email" value="{{ old('email') }}">
				</div>
				<div class="col-md-4">
					<label for="phone"> Teléfono </label>
					<input class="form-control" type="text" name="phone" id="phone" value="{{ old('phone') }}">
				</div>
				<div class="col-md-4">
					<label for="type"> Tipo </label>
					<select class="form-control select2" style="width:100%;" name="type" id="type">
	                  <option value="1" selected="selected"> Interno </option>
	                  <option value="2"> Externo </option>
	                </select>
				</div>
			</div> <!-- /. class="form-group" -->
			<div class="form-group">
				<div class="col-md-12">
					<label for="interests"> Intereses </label>
					<input class="form-control" type="text" name="interests" id="interests" value="{{ old('interests') }}">
				</div>
			</div> <!-- /. class="form-group" -->
		</div> <!-- /. class="box-body" -->
		<div class="box-footer">
			<button type="submit" class="btn btn-primary btn-block"> Registrar </button>
			<a class="btn btn-danger btn-block" href="{{ route('clients.index') }}"> Cancelar </a>
		</div> <!-- /. class="box-footer" -->
	</form>

@endsection

@section('scripts')
	<script src="{{ asset('js/functions/typeNumber.js') }}">
@endsection

resources/views/clients/edit_client.blade.php
@extends('layouts.theme')

@section('title', 'Edición de Clientes')

@section('content-header')
	<h1>
		<div class="col-md-8">
			<strong> Edición de Clientes : {{ $client->id }} </strong>
		</div>
	</h1>
	<hr>
@endsection

@section('content')
	
	@include('partials.errors') 

	<form role="form" action="{{ route('clients.update', $client->id) }}" method="POST">
		{{ csrf_field() }}
		<div class="box-body">
			<input name="_method" type="hidden" value="PATCH">
			<div class="form-group col-md-12">
				<label for="name"> Nombre </label>
				<input type="text" class="form-control" id="name" name="name" value="{{ $client->name }}">
			</div> <!-- /. class="form-group col-md-12" -->
			<div class="form-group">
				<div class="col-md-4">
					<label for="email"> E-Mail </label>
					<input type="text" class="form-control" id="email" name="email" value="{{ $client->email }}">
				</div> 
				<div class="col-md-4">
					<label for="phone"> Teléfono </label>
					<input type="text" class="form-control" id="phone" name="phone" value="{{ $client->phone }}">
				</div>
				<div class="col-md-4">
					<label for="type"> Tipo </label>
					<select class="form-control select2" style="width:100%;" id="type" name="type">
						<option value="{{ $client->type }}" selected="disabled"> {{ $client->type }} </option>
						<option value="1"> Interno </option>
						<option value="2"> Externo </option>
					</select>	
				</div>
				<div class="form-group col-md-12">
					<label for="interests"> Intereses </label>
					<input type="text" class="form-control" id="interests" name="interests" value="{{ $client->interests }}">
				</div>
			</div> <!-- /. class="form-group" -->
		</div> <!-- /. class="box-body" -->
		<div class="box-footer">
			<button type="submit" class="btn btn-primary btn-block"> Guardar </button>
			<a class="btn btn-danger btn-block" href="{{ route('clients.index') }}"> Cancelar </a>
		</div> <!-- /. class="box-footer" -->
	</form>

@endsection

@section('scripts')
	<script src="{{ asset('js/functions/typeNumber.js') }}"></script>
@endsection

resources/views/clients/index_clients.blade.php
@extends('layouts.theme')

@section('title', 'Clientes')

@section('styles')
    <link rel="stylesheet" href="{{ asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('scripts')
    <script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script>
      $(function () {
        $('#clients_table').DataTable({ 
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : true
        })
      })
    </script> 
@endsection

@section('content-header')
    <h1>
        <div class="col-md-8"><strong>Lista de Clientes</strong></div>
        <div class="col-md-4">
            <a class="btn btn-success btn-block pull-right" href="{{ route('clients.create') }}">
            <i class="fa fa-pencil-square-o"></i> NUEVO REGISTRO </a>
        </div>
    </h1>
    <hr>
@endsection

@section('content')

    @include('partials.success')
    @include('partials.delete')

    @if($clients->isEmpty())
        <div class="col-md-12">
            <div class="alert alert-warning">
                <i class="icon fa fa-warning"></i> No hay clientes registrados...
            </div>
        </div>
    
    @else
        <table id="clients_table" class="table table-condensed">
            <thead>
                <tr class="success">
                    <th> ID </th>
                    <th> Nombre </th>
                    <th> Tipo </th>
                </tr>
            </thead>
            <tbody>
                @foreach($clients as $client)
                    <tr>
                        @if($client->id == 1)
                            <td style="text-align: center">{{ $client->id }}</a></td>
                        @else
                            <td><a class="btn btn-sm btn-block bg-olive" href="{{ route('clients.show', $client->id) }}">{{ $client->id }}</a></td>
                        @endif
                        <td>{{ $client->name }}</td>
                        <td>{{ $client->type }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
            </tfoot>
        </table> <!-- /. id="clients_table" -->
    @endif
@endsection

resources/views/clients/show_client.blade.php
@extends('layouts.theme')

@section('title', 'Clientes')

@section('content-header')
    <h1><div class="col-md-8"><strong>Info. de Cliente</strong></div></h1><hr>
@endsection

@section('content')

    @include('partials.error')
    @include('partials.edit')

    <div class="col-md-12">
        <div class="box box-solid"> 
            <div class="box-header with-border">
                <h1 class="box-title"> {{ $client->id }} : {{ $client->name }} </h1>
            </div>
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>E-Mail:</dt><dd>{{ $client->email }}</dd>
                    <dt>Teléfono:</dt><dd>{{ $client->phone }}</dd>
                    <dt>Tipo:</dt><dd>{{ $client->type }}</dd>
                    <dt>Intereses:</dt><dd>{{ $client->interests }}</dd>
                </dl>
            </div>  <!-- /. class="box-body" -->
        </div> <!-- /. class="box box-solid" -->

        <div class="col-md-13">
            <div class="box box-primary">
                <div class="box-footer">
                    <a class="btn btn-primary col-md-6" href="{{ route('clients.index') }}"> Aceptar </a>
                    <a class="btn btn-success col-md-6" href="{{ route('clients.edit', $client->id) }}"> Editar </a>
                </div>
            </div> <!-- /. class="box box-primary" -->
        </div> <!-- /. class="col-md-13" -->
    </div> <!-- /. class="col-md-12" -->
@endsection