routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BorrowController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\DonorController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlantController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SwapController;
use App\Http\Controllers\UserController;


Route::get('/', function () {
    return view('welcome');
})->name('welcome');

// Authentication Routes...
Route::get('login', [ LoginController::class, 'showLoginForm' ] )->name('login');
Route::post('login', [ LoginController::class, 'login' ] );
Route::post('logout', [ LoginController::class, 'logout' ] )->name('logout');

// Registration Routes...
Route::get('register', [ RegisterController::class, 'showRegistrationForm' ] )->name('register');
Route::post('register', [ RegisterController::class, 'register' ] );

// Password Reset Routes...
Route::get('password/reset', [ ForgotPasswordController::class, 'showLinkRequestForm' ] );
Route::post('password/email', [ ForgotPasswordController::class, 'sendResetLinkEmail' ] );
Route::get('password/reset/{token}', [ ResetPasswordController::class, 'showResetForm' ] );
Route::post('password/reset', [ ResetPasswordController::class, 'reset' ] );

Route::get('/home', [ HomeController::class, 'index' ] )->name('home');

// ADMINISTRACIÓN ///////////////////////////////////////////////////////////////
Route::get('admin/cut',[ AdminController::class, 'cut' ] )->name('admin.cut');
Route::get('admin/barcodes', [ AdminController::class, 'barcodes' ] )->name('admin.barcodes');
Route::post('admin/pdf', [ AdminController::class, 'pdf' ] )->name('admin.pdf');
Route::get('admin/search/book/{title}', [ AdminController::class, 'searchbook' ] );
Route::resource('admin', AdminController::class )->only([ 'edit', 'update' ]);

// REGISTROS
Route::get('user/pass/{id}', [ UserController::class, 'showPass' ] )->name('user.changepass');
Route::patch('user/updatepass/{id}', [ UserController::class, 'updatePass' ] )->name('user.updatePass');
Route::get('user/role/{id}', [ UserController::class, 'showRole' ] )->name('user.role');
Route::patch('user/updateRole/{id}', [ UserController::class, 'updateRole' ] )->name('user.updateRole');
Route::resource('users', UserController::class );

Route::put('book/updateStock', [ BookController::class, 'updateStock' ] )->name('book.updateStock');
Route::get('book/search', [ BookController::class, 'search' ] )->name('book.search');
Route::resource('books',BookController::class);
Route::get('feature/newFeature/{book_id}', [ FeatureController::class, 'newFeature' ] )->name('feature.newFeature');
Route::resource('features', FeatureController::class )->except([ 'index', 'create', 'show' ]);

Route::resource('classifications', ClassificationController::class )->except([ 'show' ]);
Route::resource('clients', ClientController::class );
Route::resource('plants', PlantController::class );

// OPERACIONES //////////////////////////////////////////////////////////////////
Route::get('swap/search/book/{isbn}', [ SwapController::class, 'searchbook' ] );
Route::resource('swaps', SwapController::class );

Route::get('donation/donate', [ DonationController::class, 'donate' ] )->name('donation.donate');
Route::get('donation/receive', [ DonationController::class, 'receive' ] )->name('donation.receive');
Route::resource('donations', DonationController::class )->except([ 'create', 'edit', 'update' ]);
Route::resource('donors', DonorController::class )->except([ 'show' ]);

Route::get('borrow/search/book/{isbn}', [ BorrowController::class, 'searchbook' ] );
Route::get('devolution/search/book/{isbn}', [ BorrowController::class, 'searchborrowedbook' ] )->name('devolution.search.book');
Route::resource('borrows', BorrowController::class )->except([ 'destroy' ]);

// VENTAS ///////////////////////////////////////////////////////////////////////
Route::get('sale/search/book/{isbn}', [ SaleController::class, 'searchbook' ] )->name('searchbook');
Route::get('sale/search/plant/{id}', [ SaleController::class, 'searchplant' ] )->name('searchplant');
Route::resource('sales', SaleController::class )->except([ 'edit', 'update', 'destroy' ]);
/////////////////////////////////////////////////////////////////////////////////

app/Models/Classification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Classification extends Model
{
    protected $fillable = [ 'name', 'type' ];

    protected $table = 'classifications';

    public $timestamps = false;
}

app/Http/Controllers/ClassificationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Models\Classification;

class ClassificationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * función para listar las clasificaciones registradas en la base de datos
     * 
     * @return View con la lista de las clasificaciones
     */
    public function index()
    {
        return view('classifications.index_classes', [ 'classes' => Classification::all() ]);
    }

    /**
     * función para renderizar el formulario de creación de clasificaciones
     * 
     * @return View con el formulario de creación
     */
    public function create()
    {
        return view('classifications.create_class');
    }
    
    /**
     * función para almacenar las clasificaciones creadas desde el formulario en la base de datos
     * 
     * @param Request con la información de la clasificacion a guardar
     * @return Redirect hacia la lista de clasificaciones con el mensaje correspondiente
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'type' => 'required'
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        Classification::create($request->all());
        return redirect()->action([ ClassificationController::class, 'index' ])->with('success','La clase se ha registrado exitosamente!...');
    }

    public function edit($id)
    {
        return view('classifications.edit_class', [ 'class' => Classification::findOrFail($id) ]);
    }

    /**
     * función para actualizar la informacion de las clasificaciones registradas
     * 
     * @param Request con la nueva informacion de la clasificación
     * @param Integer con el $id de la clasificación a actualizar
     * @return Redirect hacia la lista de clasificaciones con el mensaje correspondiente
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name'     => 'required'
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        Classification::where('id',$id)->update($request->except('_token','_method'));
        return redirect()->action([ ClassificationController::class, 'index' ])->with('edit','La clase se ha modificado exitosamente!...');
    }

    /**
     * función para eliminar las clasificaciones registradas en la base de datos
     * 
     * @return Redirect hacia la lista de clasificaciones registradas con el mensaje correspondiente
     */
    public function destroy($id)
    {
        Classification::findOrFail($id)->delete();
        return redirect()->action([ ClassificationController::class, 'index' ])->with('delete', 'La clase se ha eliminado exitosamente!...');
    }
}

resources/views/classifications/create_class.blade.php
@extends('layouts.theme')

@section('title', 'Registro de Clasificaciones')

@section('content-header')
	<h1><div class="col-md-8"><strong> Registro de Clasificación </strong></div></h1><hr>
@endsection

@section('content')

	@include('partials.errors')

	<form role="form" action="{{ route('classifications.store') }}" method="POST" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="box-body"> 
			<div class="form-group col-md-12">
				<label for="class"> Clasificación: </label>
				<input type="text" class="form-control" id="name" name="name">
			</div> <!-- /. -->
			<div class="form-group col-md-12">
				<p> Tipo: &nbsp&nbsp&nbsp
					<input type="radio" name="type" value="Libro" class="flat-red">
					<label for="type"> Libro &nbsp&nbsp</label>
					<input type="radio" name="type" value="Planta" class="flat-red">
					<label for="type"> Planta </label>
				</p>
			</div> <!-- /. class="form-group col-md-12" -->
		</div> <!-- /. class="box-body" -->
		<div class="box-footer">
			<button type="submit" class="btn btn-primary btn-block"> Registrar </button>
			<a class="btn btn-danger btn-block" href="{{ route('classifications.index') }}"> Cancel </a>
		</div> <!-- /. class="box-footer" -->
	</form>

@endsection

resources/views/classifications/edit_class.blade.php
@extends('layouts.theme')

@section('title', 'Edición de Clasificación')

@section('content-header')
    <h1><div class="col-md-8"><strong> Edición de Clasificación : {{ $class->id }}</strong></div></h1><hr>
@endsection

@section('content')

    @include('partials.errors')

    <form role="form" action="{{ route('classifications.update', $class->id) }}" method="POST">
        {{ csrf_field() }}
        <div class="box-body"> 
            <input name="_method" type="hidden" value="PATCH">
            <div class="form-group col-md-12">
                <label for="class"> Nombre </label> 
                <input type="text" class="form-control" id="name" name="name" value="{{ $class->name }}">
            </div> <!-- /. class="form-group col-md-12" -->
        </div> <!-- /. class="box-body" -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary btn-block"> Guardar </button>
            <a class="btn btn-danger btn-block" href="{{ route('classifications.index') }}"> Cancelar </a>
        </div>  <!-- /. class="box-footer" -->
    </form>

@endsection

resources/views/classifications/index_classes.blade.php
@extends('layouts.theme')

@section('title', 'Clasificaciones')

@section('styles')
    <link rel="stylesheet" href="{{ asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('scripts')
    <script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script>
      $(function () {
        $('#classesTable').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true, 
          'info'        : true,
          'autoWidth'   : true
        })
      })
    </script> 
@endsection

@section('content-header')
	<h1>
		<div class="col-md-8">
			<strong>Lista de Clasificaciones</strong>
		</div>
		<div class="col-md-4">
			<a class="btn btn-success btn-block pull-right" href="{{ route('classifications.create') }}">
			<i class="fa fa-pencil-square-o"></i> NUEVO REGISTRO </a>
		</div>
	</h1> 
	<hr>
@endsection

@section('content')

	@include('partials.success')
	@include('partials.delete')
	@include('partials.edit')

	@if($classes->isEmpty())
        <div class="col-md-12">
            <div class="alert alert-warning">
                <i class="icon fa fa-warning"></i>No hay clasificaciones registradas...
            </div>
        </div>

	@else
        <table id="classesTable" class="table table-bordered table-striped">
	        <thead>
	            <tr class="success">
	                <th> Nombre </th>
	                <th> Tipo </th> 
	                <th> Editar </th>
	                <th> Eliminar </th>
	            </tr>
	        </thead>
	        <tbody>
	            @foreach($classes as $class)
	            <tr>
	                <td>{{ $class->name }}</a></td>
	                <td style="width:20%">{{ $class->type }}</td>
	                <td style="width:10%">
	                	<a class="btn btn-sm btn-block btn-info" href="{{ route('classifications.edit', $class->id) }}"><i class="icon fa fa-pencil"></i></a>
	                </td>
	                <td style="width:10%">
	                	<form role="form" action="{{ route('classifications.destroy', $class->id) }}" method="POST">
		                    {{ csrf_field() }}
		                    <input type="hidden" name="_method" value="DELETE">
		                    <button type="submit" class="btn btn-sm btn-block btn-danger">
		                    	<i class="icon fa fa-trash"></i>
		                    </button>
		                </form>
	                </td>
	            </tr>
	            @endforeach
	        </tbody>
		</table> <!-- /. id="classesTable" -->
	@endif
@endsection